export const STYLES = {
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica Neue', Arial, sans-serif",
    colors: {
      text: "#0f172a",
      textMuted: "#64748b",
      textPlaceholder: "#94a3b8",
      background: "#ffffff",
      backgroundLight: "#f8fafc",
      border: "#e2e8f0",
      badgeSuccess: "#10b981",
      badgeError: "#ef4444",
      accentBlue: "#6366f1",
      accentPurple: "#8b5cf6",
    },
  } as const;
  
  export const LABEL_TRANSLATIONS: Record<string, string> = {
    socialDenomination: "Denominación Social",
    cuitNumber: "Número de CUIT",
    societyType: "Tipo de Sociedad",
    order: "Orden",
    sector: "Sector",
    activityType: "Tipo de Actividad",
    activityStartDate: "Fecha de Inicio de Actividad",
    countryOfInscription: "País de Inscripción",
    inscriptIn: "Inscripto en",
    inscriptionNumber: "Número de Inscripción",
    email: "Correo Electrónico",
    phone: "Teléfono",
    address: "Dirección",
    city: "Ciudad",
    province: "Provincia",
    postalCode: "Código Postal",
    clientIp: "IP del Cliente",
    legalAddress: "Dirección Legal",
    realAddress: "Dirección Real",
    street: "Calle",
    subjectObliged: "Sujeto Obligado",
    fiscalResidenceArgentina: "Residencia Fiscal Argentina",
    fiscalResidenceCountry: "País de Residencia Fiscal",
    fiscalResidenceAddress: "Dirección de Residencia Fiscal",
    finalBeneficiaries: "Beneficiarios Finales",
    directors: "Directores",
    name: "Nombre",
    document: "Documento",
    percentage: "Porcentaje",
    position: "Cargo",
    acceptTerms: "Acepta Términos",
    comments: "Comentarios",
    additionalInfo: "Información Adicional",
  };
  
  export const CATEGORY_TRANSLATIONS: Record<string, string> = {
    balance: "Balance",
    statute: "Estatuto",
    designAuthorities: "Designación de Autoridades",
    dniFront: "DNI Frente",
    dniBack: "DNI Dorso",
    unknown: "Desconocido",
  };
  